development:
  host: 'localhost'
  port: 6379

test:
  host: 'localhost'
  port: 6379

production:
  host: 'herring.redistogo.com'
  username: 'redistogo'
  password: '4edf5d726c519fbd2f1007cf3e5cc751'
  port: 9079